/**
 * Canteen Menu Seed — ZovikPOS AI-Powered POS
 * Seeds all 36 real canteen menu items into Supabase.
 * Safe to re-run: clears existing items before seeding.
 */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// ─── Authentic image URLs per food type ──────────────────────────────────────
const IMG = {
  chickenBiryani: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
  beefBiryani:    'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&auto=format&fit=crop&q=80',
  qeema:          'https://images.unsplash.com/photo-1645696301019-35adcc18a1ee?w=600&auto=format&fit=crop&q=80',
  alooQeema:      'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=600&auto=format&fit=crop&q=80',
  daalChawal:     'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
  daalFry:        'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&auto=format&fit=crop&q=80',
  chapati:        'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=600&auto=format&fit=crop&q=80',
  paratha:        'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
  omelette:       'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&auto=format&fit=crop&q=80',
  chickenRoll:    'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
  zingerBurger:   'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
  cheeseBurger:   'https://images.unsplash.com/photo-1550317138-10000687a72b?w=600&auto=format&fit=crop&q=80',
  bunShami:       'https://images.unsplash.com/photo-1461009683693-342af2f2d6ce?w=600&auto=format&fit=crop&q=80',
  shawarma:       'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=600&auto=format&fit=crop&q=80',
  samosa:         'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
  springRoll:     'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=600&auto=format&fit=crop&q=80',
  tea:            'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&auto=format&fit=crop&q=80',
  friesPlain:     'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
  friesLoaded:    'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=600&auto=format&fit=crop&q=80',
};

const menuItems = [
  // ── LUNCH ──────────────────────────────────────────────────────────────────
  {
    name: 'Chicken Biryani / Pulao',
    groupName: 'Chicken Biryani / Pulao',
    category: 'Lunch',
    unit: '250 gm',
    price: 185,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.chickenBiryani,
    description: 'Fragrant basmati rice cooked with tender chicken in aromatic spices.',
  },
  {
    name: 'Chicken Biryani / Pulao',
    groupName: 'Chicken Biryani / Pulao',
    category: 'Lunch',
    unit: '500 gm',
    price: 290,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.chickenBiryani,
    description: 'Fragrant basmati rice cooked with tender chicken in aromatic spices.',
  },
  {
    name: 'Beef Biryani / Pulao',
    groupName: 'Beef Biryani / Pulao',
    category: 'Lunch',
    unit: '250 gm',
    price: 210,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.beefBiryani,
    description: 'Rich and hearty beef biryani slow-cooked with whole spices and saffron.',
  },
  {
    name: 'Beef Biryani / Pulao',
    groupName: 'Beef Biryani / Pulao',
    category: 'Lunch',
    unit: '500 gm',
    price: 290,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.beefBiryani,
    description: 'Rich and hearty beef biryani slow-cooked with whole spices and saffron.',
  },
  {
    name: 'Chicken / Beef Qeema / Achari',
    category: 'Lunch',
    unit: '200 gm',
    price: 230,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.qeema,
    description: 'Spiced minced meat cooked with onions, tomatoes and whole spices.',
  },
  {
    name: 'Aloo Qeema',
    category: 'Lunch',
    unit: '200 gm',
    price: 220,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.alooQeema,
    description: 'Classic Pakistani minced meat with tender potato chunks.',
  },
  {
    name: 'Daal & Chawal',
    category: 'Lunch',
    unit: '250 gm',
    price: 180,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.daalChawal,
    description: 'Comforting lentils served with steamed basmati rice.',
  },
  {
    name: 'Daal Fry / Mixed Vegetable',
    category: 'Lunch',
    unit: '200 gm',
    price: 180,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.daalFry,
    description: 'Freshly tempered lentils or seasonal mixed vegetables with cumin.',
  },
  {
    name: 'Chapati',
    category: 'Lunch',
    unit: '1 No.',
    price: 20,
    type: 'food',
    prepTime: 3,
    stock: 200,
    imageUrl: IMG.chapati,
    description: 'Freshly baked whole wheat flatbread.',
  },

  // ── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    name: 'Paratha Ordinary',
    category: 'Breakfast',
    unit: '1 No.',
    price: 50,
    type: 'food',
    prepTime: 5,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Crispy flaky layered flatbread, freshly made on tawa.',
  },
  {
    name: 'Egg Omelette / Half Fry',
    category: 'Breakfast',
    unit: '1 No.',
    price: 60,
    type: 'food',
    prepTime: 5,
    stock: 100,
    imageUrl: IMG.omelette,
    description: 'Freshly cooked egg omelette or half-fry with spices.',
  },
  {
    name: 'Paratha Aloo',
    category: 'Breakfast',
    unit: '1 No.',
    price: 130,
    type: 'food',
    prepTime: 6,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Stuffed paratha with spiced mashed potato filling.',
  },
  {
    name: 'Paratha Cheese',
    category: 'Breakfast',
    unit: '1 No.',
    price: 200,
    type: 'food',
    prepTime: 6,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Flaky paratha stuffed with melted cheese.',
  },
  {
    name: 'Paratha Chicken',
    category: 'Breakfast',
    unit: '1 No.',
    price: 200,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Paratha stuffed with seasoned chicken filling.',
  },
  {
    name: 'Paratha Chicken Cheese',
    category: 'Breakfast',
    unit: '1 No.',
    price: 220,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Premium paratha with chicken and melted cheese filling.',
  },
  {
    name: 'Paratha Qeema',
    category: 'Breakfast',
    unit: '1 No.',
    price: 220,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Crispy paratha stuffed with spiced minced meat.',
  },

  // ── FAST FOOD ──────────────────────────────────────────────────────────────
  {
    name: 'Chicken Chatni / Boti Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 190,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.chickenRoll,
    description: 'Tender chicken boti wrapped in a flaky paratha with chatni.',
  },
  {
    name: 'Chicken Malai / Mayo Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 200,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.chickenRoll,
    description: 'Creamy malai chicken or mayo chicken wrapped in soft paratha.',
  },
  {
    name: 'Chicken Cheese / Crispy Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 250,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.chickenRoll,
    description: 'Crispy fried chicken with melted cheese in a paratha roll.',
  },
  {
    name: 'Chicken Twister / Zinger Burger / Club Sandwich',
    category: 'Fast Food',
    unit: '1 No.',
    price: 290,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.zingerBurger,
    description: 'Crispy chicken zinger burger or twister wrap or classic club sandwich.',
  },
  {
    name: 'Chicken / Zinger Burger with Cheese',
    category: 'Fast Food',
    unit: '1 No.',
    price: 345,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.cheeseBurger,
    description: 'Crispy chicken burger loaded with melted cheese and fresh toppings.',
  },
  {
    name: 'Bun Shami Kabab / Sandwich / Burger',
    category: 'Fast Food',
    unit: '1 No.',
    price: 120,
    type: 'food',
    prepTime: 5,
    stock: 100,
    imageUrl: IMG.bunShami,
    description: 'Classic bun kabab with shami patty, chatni and fresh salad.',
  },
  {
    name: 'Chicken Shawarma',
    category: 'Fast Food',
    unit: '1 No.',
    price: 270,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.shawarma,
    description: 'Juicy marinated chicken wrapped in bread with garlic sauce and veggies.',
  },

  // ── REFRESHMENT ────────────────────────────────────────────────────────────
  {
    name: 'Aloo Samosa',
    category: 'Refreshment',
    unit: '1 No.',
    price: 40,
    type: 'food',
    prepTime: 3,
    stock: 200,
    imageUrl: IMG.samosa,
    description: 'Golden crispy pastry filled with spiced potato and herbs.',
  },
  {
    name: 'Spring Roll',
    category: 'Refreshment',
    unit: '1 No.',
    price: 40,
    type: 'food',
    prepTime: 3,
    stock: 200,
    imageUrl: IMG.springRoll,
    description: 'Crispy fried roll filled with vegetables and seasoning.',
  },
  {
    name: 'Tea',
    category: 'Refreshment',
    unit: '1 Cup',
    price: 70,
    type: 'drink',
    prepTime: 4,
    stock: 200,
    imageUrl: IMG.tea,
    description: 'Hot freshly brewed desi chai with milk and cardamom.',
  },
  {
    name: 'Fries Plain',
    category: 'Refreshment',
    unit: '1 Plate',
    price: 170,
    type: 'food',
    prepTime: 6,
    stock: 100,
    imageUrl: IMG.friesPlain,
    description: 'Golden crispy French fries, lightly salted.',
  },
  {
    name: 'Fries Masala',
    category: 'Refreshment',
    unit: '1 Box',
    price: 170,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Crispy fries tossed with our signature masala spice blend.',
  },
  {
    name: 'Fries Mayo Garlic',
    category: 'Refreshment',
    unit: '1 Box',
    price: 170,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Golden fries drizzled with creamy garlic mayo sauce.',
  },
  {
    name: 'Fries BBQ',
    category: 'Refreshment',
    unit: '1 Box',
    price: 170,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Crispy fries coated in smoky BBQ seasoning.',
  },
  {
    name: 'Fries BBQ Cheese',
    category: 'Refreshment',
    unit: '1 Box',
    price: 180,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'BBQ fries topped with melted cheese sauce.',
  },
  {
    name: 'Fries Pizza',
    category: 'Refreshment',
    unit: '1 Box',
    price: 500,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Loaded fries with pizza sauce, mozzarella and toppings.',
  },
  {
    name: 'Fries Chicken Steak',
    category: 'Refreshment',
    unit: '1 Box',
    price: 400,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Fries loaded with grilled chicken steak slices and sauces.',
  },
  {
    name: 'Fries Mexican',
    category: 'Refreshment',
    unit: '1 Box',
    price: 400,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Spicy Mexican style fries with jalapeños and salsa.',
  },
  {
    name: 'Fries Veggie',
    category: 'Refreshment',
    unit: '1 Box',
    price: 280,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Fries topped with fresh vegetables and house dressing.',
  },
  {
    name: 'Fries Smiley',
    category: 'Refreshment',
    unit: '1 Box',
    price: 300,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.friesPlain,
    description: 'Fun smiley-shaped potato snacks, crispy and golden.',
  },
];

async function seedCanteenMenu() {
  console.log('🌱 Starting canteen menu seed...\n');

  try {
    // Clear existing menu data safely
    console.log('Clearing existing menu items...');
    await prisma.cartItem.deleteMany({});
    await prisma.orderItem.deleteMany({});
    await prisma.menuItem.deleteMany({});
    console.log('✅ Existing items cleared.\n');

    // Seed all items
    console.log(`Seeding ${menuItems.length} menu items...`);
    for (const item of menuItems) {
      await prisma.menuItem.create({ data: { ...item, isActive: true } });
      process.stdout.write('.');
    }

    console.log('\n\n✅ All menu items seeded successfully!');
    console.log(`\n📊 Summary:`);

    const counts = await prisma.menuItem.groupBy({
      by: ['category'],
      _count: { id: true },
    });
    counts.forEach(c => console.log(`  ${c.category}: ${c._count.id} items`));

    const total = await prisma.menuItem.count();
    console.log(`\n  TOTAL: ${total} records in database`);
    console.log('\n🎉 Canteen menu is ready!\n');
  } catch (err) {
    console.error('\n❌ Seed error:', err.message);
  } finally {
    await prisma.$disconnect();
  }
}

seedCanteenMenu();
