/**
 * Canteen Menu Seed — Split Clean Items (No slashes '/')
 * Seeds clean, individual menu items with distinct names & authentic images.
 */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// ─── Authentic image URLs per specific food type ─────────────────────────────
const IMG = {
  chickenBiryani:  'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=700&auto=format&fit=crop&q=80',
  chickenPulao:    'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=700&auto=format&fit=crop&q=80',
  beefBiryani:     'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=700&auto=format&fit=crop&q=80',
  beefPulao:       'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=700&auto=format&fit=crop&q=80',
  chickenQeema:    'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=700&auto=format&fit=crop&q=80',
  beefQeema:       'https://images.unsplash.com/photo-1645696301019-35adcc18a1ee?w=700&auto=format&fit=crop&q=80',
  achariQeema:     'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=700&auto=format&fit=crop&q=80',
  alooQeema:       'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=700&auto=format&fit=crop&q=80',
  daalChawal:      'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=700&auto=format&fit=crop&q=80',
  daalFry:         'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=700&auto=format&fit=crop&q=80',
  mixVeg:          'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=700&auto=format&fit=crop&q=80',
  chapati:         'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=700&auto=format&fit=crop&q=80',
  paratha:         'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=700&auto=format&fit=crop&q=80',
  omelette:        'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=700&auto=format&fit=crop&q=80',
  halfFry:         'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=700&auto=format&fit=crop&q=80',
  chickenRoll:     'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=700&auto=format&fit=crop&q=80',
  botiRoll:        'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=700&auto=format&fit=crop&q=80',
  malaiRoll:       'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=700&auto=format&fit=crop&q=80',
  mayoRoll:        'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=700&auto=format&fit=crop&q=80',
  cheeseRoll:      'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=700&auto=format&fit=crop&q=80',
  crispyRoll:      'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=700&auto=format&fit=crop&q=80',
  twisterWrap:     'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=700&auto=format&fit=crop&q=80',
  zingerBurger:    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=700&auto=format&fit=crop&q=80',
  clubSandwich:    'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=700&auto=format&fit=crop&q=80',
  cheeseBurger:    'https://images.unsplash.com/photo-1550317138-10000687a72b?w=700&auto=format&fit=crop&q=80',
  bunShami:        'https://images.unsplash.com/photo-1461009683693-342af2f2d6ce?w=700&auto=format&fit=crop&q=80',
  chickenSandwich: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=700&auto=format&fit=crop&q=80',
  chickenBurger:   'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=700&auto=format&fit=crop&q=80',
  shawarma:        'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=700&auto=format&fit=crop&q=80',
  samosa:          'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&auto=format&fit=crop&q=80',
  springRoll:      'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=700&auto=format&fit=crop&q=80',
  tea:             'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=700&auto=format&fit=crop&q=80',
  friesPlain:      'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=700&auto=format&fit=crop&q=80',
  friesLoaded:     'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=700&auto=format&fit=crop&q=80',
};

const menuItems = [
  // ── LUNCH ──────────────────────────────────────────────────────────────────
  {
    name: 'Chicken Biryani',
    groupName: 'Chicken Biryani',
    category: 'Lunch',
    unit: '250 gm',
    price: 185,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.chickenBiryani,
    description: 'Fragrant basmati rice cooked with tender chicken in aromatic spices.',
  },
  {
    name: 'Chicken Biryani',
    groupName: 'Chicken Biryani',
    category: 'Lunch',
    unit: '500 gm',
    price: 290,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.chickenBiryani,
    description: 'Fragrant basmati rice cooked with tender chicken in aromatic spices.',
  },
  {
    name: 'Chicken Pulao',
    groupName: 'Chicken Pulao',
    category: 'Lunch',
    unit: '250 gm',
    price: 185,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.chickenPulao,
    description: 'Traditional mild spiced chicken pulao cooked in rich stock.',
  },
  {
    name: 'Chicken Pulao',
    groupName: 'Chicken Pulao',
    category: 'Lunch',
    unit: '500 gm',
    price: 290,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.chickenPulao,
    description: 'Traditional mild spiced chicken pulao cooked in rich stock.',
  },
  {
    name: 'Beef Biryani',
    groupName: 'Beef Biryani',
    category: 'Lunch',
    unit: '250 gm',
    price: 210,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.beefBiryani,
    description: 'Rich and hearty beef biryani slow-cooked with whole spices.',
  },
  {
    name: 'Beef Biryani',
    groupName: 'Beef Biryani',
    category: 'Lunch',
    unit: '500 gm',
    price: 290,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.beefBiryani,
    description: 'Rich and hearty beef biryani slow-cooked with whole spices.',
  },
  {
    name: 'Beef Pulao',
    groupName: 'Beef Pulao',
    category: 'Lunch',
    unit: '250 gm',
    price: 210,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.beefPulao,
    description: 'Aromatic beef pulao with tender meat chunks and spices.',
  },
  {
    name: 'Beef Pulao',
    groupName: 'Beef Pulao',
    category: 'Lunch',
    unit: '500 gm',
    price: 290,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.beefPulao,
    description: 'Aromatic beef pulao with tender meat chunks and spices.',
  },
  {
    name: 'Chicken Qeema',
    category: 'Lunch',
    unit: '200 gm',
    price: 230,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.chickenQeema,
    description: 'Spiced minced chicken cooked with onions, tomatoes and green chillies.',
  },
  {
    name: 'Beef Qeema',
    category: 'Lunch',
    unit: '200 gm',
    price: 230,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.beefQeema,
    description: 'Flavorful minced beef cooked with aromatic whole spices.',
  },
  {
    name: 'Achari Qeema',
    category: 'Lunch',
    unit: '200 gm',
    price: 230,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.achariQeema,
    description: 'Tangy pickle-spiced minced meat cooked to perfection.',
  },
  {
    name: 'Aloo Qeema',
    category: 'Lunch',
    unit: '200 gm',
    price: 220,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.alooQeema,
    description: 'Classic Pakistani minced meat with tender potato chunks.',
  },
  {
    name: 'Daal & Chawal',
    category: 'Lunch',
    unit: '250 gm',
    price: 180,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.daalChawal,
    description: 'Comforting yellow lentils served with hot basmati rice.',
  },
  {
    name: 'Daal Fry',
    category: 'Lunch',
    unit: '200 gm',
    price: 180,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.daalFry,
    description: 'Freshly tempered lentils with garlic, cumin, and butter.',
  },
  {
    name: 'Mixed Vegetable',
    category: 'Lunch',
    unit: '200 gm',
    price: 180,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.mixVeg,
    description: 'Seasonal fresh garden vegetables cooked in spicy gravy.',
  },
  {
    name: 'Chapati',
    category: 'Lunch',
    unit: '1 No.',
    price: 20,
    type: 'food',
    prepTime: 3,
    stock: 200,
    imageUrl: IMG.chapati,
    description: 'Freshly baked soft whole wheat flatbread.',
  },

  // ── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    name: 'Paratha Ordinary',
    category: 'Breakfast',
    unit: '1 No.',
    price: 50,
    type: 'food',
    prepTime: 5,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Crispy flaky layered flatbread, freshly made on tawa.',
  },
  {
    name: 'Egg Omelette',
    category: 'Breakfast',
    unit: '1 No.',
    price: 60,
    type: 'food',
    prepTime: 5,
    stock: 100,
    imageUrl: IMG.omelette,
    description: 'Freshly beaten egg omelette with onions, tomatoes and herbs.',
  },
  {
    name: 'Egg Half Fry',
    category: 'Breakfast',
    unit: '1 No.',
    price: 60,
    type: 'food',
    prepTime: 4,
    stock: 100,
    imageUrl: IMG.halfFry,
    description: 'Sunny-side-up half fry egg sprinkled with black pepper.',
  },
  {
    name: 'Paratha Aloo',
    category: 'Breakfast',
    unit: '1 No.',
    price: 130,
    type: 'food',
    prepTime: 6,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Stuffed paratha with spiced mashed potato filling.',
  },
  {
    name: 'Paratha Cheese',
    category: 'Breakfast',
    unit: '1 No.',
    price: 200,
    type: 'food',
    prepTime: 6,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Flaky paratha stuffed with melted gooey cheese.',
  },
  {
    name: 'Paratha Chicken',
    category: 'Breakfast',
    unit: '1 No.',
    price: 200,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Crispy paratha stuffed with seasoned chicken filling.',
  },
  {
    name: 'Paratha Chicken Cheese',
    category: 'Breakfast',
    unit: '1 No.',
    price: 220,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Premium paratha with chicken and melted cheese filling.',
  },
  {
    name: 'Paratha Qeema',
    category: 'Breakfast',
    unit: '1 No.',
    price: 220,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.paratha,
    description: 'Golden paratha stuffed with spiced minced meat.',
  },

  // ── FAST FOOD ──────────────────────────────────────────────────────────────
  {
    name: 'Chicken Chatni Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 190,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.chickenRoll,
    description: 'Tender chicken boti wrapped with spicy green chatni in a paratha.',
  },
  {
    name: 'Chicken Boti Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 190,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.botiRoll,
    description: 'Smoky grilled chicken boti wrapped in crispy paratha.',
  },
  {
    name: 'Chicken Malai Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 200,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.malaiRoll,
    description: 'Melt-in-mouth creamy malai boti wrapped in soft paratha roll.',
  },
  {
    name: 'Chicken Mayo Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 200,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.mayoRoll,
    description: 'Juicy chicken boti loaded with rich mayo garlic sauce in paratha.',
  },
  {
    name: 'Chicken Cheese Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 250,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.cheeseRoll,
    description: 'Chicken boti roll packed with melted mozzarella cheese.',
  },
  {
    name: 'Crispy Chicken Roll',
    category: 'Fast Food',
    unit: '150 gm',
    price: 250,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.crispyRoll,
    description: 'Crispy fried chicken strips wrapped in a warm paratha roll.',
  },
  {
    name: 'Chicken Twister Wrap',
    category: 'Fast Food',
    unit: '1 No.',
    price: 290,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.twisterWrap,
    description: 'Crispy chicken strips, lettuce and sauce wrapped in a tortilla.',
  },
  {
    name: 'Zinger Burger',
    category: 'Fast Food',
    unit: '1 No.',
    price: 290,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.zingerBurger,
    description: 'Crispy deep-fried zinger fillet with lettuce and mayo in a soft bun.',
  },
  {
    name: 'Club Sandwich',
    category: 'Fast Food',
    unit: '1 No.',
    price: 290,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.clubSandwich,
    description: 'Classic triple-decker sandwich with chicken, egg, mayo and salad.',
  },
  {
    name: 'Chicken Burger with Cheese',
    category: 'Fast Food',
    unit: '1 No.',
    price: 345,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.cheeseBurger,
    description: 'Juicy chicken patty topped with a slice of melted cheese.',
  },
  {
    name: 'Zinger Burger with Cheese',
    category: 'Fast Food',
    unit: '1 No.',
    price: 345,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.cheeseBurger,
    description: 'Crispy zinger burger loaded with melted cheese slice and spicy mayo.',
  },
  {
    name: 'Bun Shami Kabab',
    category: 'Fast Food',
    unit: '1 No.',
    price: 120,
    type: 'food',
    prepTime: 5,
    stock: 100,
    imageUrl: IMG.bunShami,
    description: 'Traditional street-style bun kabab with spicy shami patty and chatni.',
  },
  {
    name: 'Chicken Sandwich',
    category: 'Fast Food',
    unit: '1 No.',
    price: 120,
    type: 'food',
    prepTime: 5,
    stock: 100,
    imageUrl: IMG.chickenSandwich,
    description: 'Fresh toasted sandwich with creamy chicken spread.',
  },
  {
    name: 'Chicken Burger',
    category: 'Fast Food',
    unit: '1 No.',
    price: 120,
    type: 'food',
    prepTime: 6,
    stock: 100,
    imageUrl: IMG.chickenBurger,
    description: 'Delicious chicken patty burger with garlic mayo and lettuce.',
  },
  {
    name: 'Chicken Shawarma',
    category: 'Fast Food',
    unit: '1 No.',
    price: 270,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.shawarma,
    description: 'Shredded roasted chicken wrapped in pita bread with garlic sauce.',
  },

  // ── REFRESHMENT ────────────────────────────────────────────────────────────
  {
    name: 'Aloo Samosa',
    category: 'Refreshment',
    unit: '1 No.',
    price: 40,
    type: 'food',
    prepTime: 3,
    stock: 200,
    imageUrl: IMG.samosa,
    description: 'Golden crispy pastry filled with spiced potato and herbs.',
  },
  {
    name: 'Spring Roll',
    category: 'Refreshment',
    unit: '1 No.',
    price: 40,
    type: 'food',
    prepTime: 3,
    stock: 200,
    imageUrl: IMG.springRoll,
    description: 'Crispy fried roll filled with seasoned vegetables.',
  },
  {
    name: 'Tea',
    category: 'Refreshment',
    unit: '1 Cup',
    price: 70,
    type: 'drink',
    prepTime: 4,
    stock: 200,
    imageUrl: IMG.tea,
    description: 'Hot freshly brewed desi chai with milk and cardamom.',
  },
  {
    name: 'Fries Plain',
    category: 'Refreshment',
    unit: '1 Plate',
    price: 170,
    type: 'food',
    prepTime: 6,
    stock: 100,
    imageUrl: IMG.friesPlain,
    description: 'Golden crispy French fries, lightly salted.',
  },
  {
    name: 'Fries Masala',
    category: 'Refreshment',
    unit: '1 Box',
    price: 170,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Crispy fries tossed with our signature masala spice blend.',
  },
  {
    name: 'Fries Mayo Garlic',
    category: 'Refreshment',
    unit: '1 Box',
    price: 170,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Golden fries drizzled with creamy garlic mayo sauce.',
  },
  {
    name: 'Fries BBQ',
    category: 'Refreshment',
    unit: '1 Box',
    price: 170,
    type: 'food',
    prepTime: 7,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Crispy fries coated in smoky BBQ seasoning.',
  },
  {
    name: 'Fries BBQ Cheese',
    category: 'Refreshment',
    unit: '1 Box',
    price: 180,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'BBQ fries topped with melted cheese sauce.',
  },
  {
    name: 'Fries Pizza',
    category: 'Refreshment',
    unit: '1 Box',
    price: 500,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Loaded fries with pizza sauce, mozzarella and toppings.',
  },
  {
    name: 'Fries Chicken Steak',
    category: 'Refreshment',
    unit: '1 Box',
    price: 400,
    type: 'food',
    prepTime: 12,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Fries loaded with grilled chicken steak slices and sauces.',
  },
  {
    name: 'Fries Mexican',
    category: 'Refreshment',
    unit: '1 Box',
    price: 400,
    type: 'food',
    prepTime: 10,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Spicy Mexican style fries with jalapeños and salsa.',
  },
  {
    name: 'Fries Veggie',
    category: 'Refreshment',
    unit: '1 Box',
    price: 280,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.friesLoaded,
    description: 'Fries topped with fresh vegetables and house dressing.',
  },
  {
    name: 'Fries Smiley',
    category: 'Refreshment',
    unit: '1 Box',
    price: 300,
    type: 'food',
    prepTime: 8,
    stock: 100,
    imageUrl: IMG.friesPlain,
    description: 'Fun smiley-shaped potato snacks, crispy and golden.',
  },
];

async function seedCleanMenu() {
  console.log('🌱 Seeding Clean Menu Items (No "/" in names)...');

  try {
    // Clear existing cart and order references first
    await prisma.cartItem.deleteMany({});
    await prisma.orderItem.deleteMany({});
    await prisma.menuItem.deleteMany({});
    console.log('✅ Previous menu items cleared.');

    let inserted = 0;
    for (const item of menuItems) {
      await prisma.menuItem.create({
        data: {
          ...item,
          isActive: true,
        },
      });
      inserted++;
    }

    console.log(`\n🎉 Successfully seeded ${inserted} individual, clean menu items into database!`);
  } catch (err) {
    console.error('❌ Seed error:', err);
  } finally {
    await prisma.$disconnect();
  }
}

seedCleanMenu();
